feat(LOC-4829): ContextMenu submenu
getflywheel/local-components pull request #309
Opened 2023-03-02 15:36 UTC by adamperrry

This PR adds a bit of refactoring as well as a new feature to ContextMenu - submenus!

It uses a recursive approach to render and items with submenus. 

Pulls out the TextButton items into its own component, tweaks several styles, and adds the `checkbox` type.

Commit messages have more details!

2023-03-07 19:54 UTC, bgturner requested changes
Visually, using the Context Menu within Storybook feels great! The animations look good and keyboard nav feels intuitive! When looking at the underlying markup and implementation, I have a nit-pick resolution, and a few questions:

## Nit-pick
-   Separator needs a `role="separator"`
    - See: https://www.w3.org/WAI/tutorials/menus/application-menus/#additional-markup

![Image 2023-03-07 at 10 41 37 AM](https://user-images.githubusercontent.com/299432/223537376-666442b4-0a0c-47f1-b2f2-071f0ddc5bb2.jpg)


## Questions

### Using Tooltip component

-   Can you help me better understand the reasons for using a Tooltip to render the context menu? Part of me wonders if we're forcing the Tooltip component to do more than it should.
    -   For example, as I look at the rendered markup, I notice that the actual menu shows up in a completely different place in the DOM. I get that this is due to the Popper library needing to&#x2026; do stuff? But part of me wonders if things like a11y functionality would be easier to implement if the menus rendered markup where the component was called as opposed to multiple Tooltips.

![Image 2023-03-07 at 11 40 58 AM](https://user-images.githubusercontent.com/299432/223537576-e9b5963f-58d5-4606-8ed8-677f0f7e93b8.jpg)


### Custom hook for mouse state

-   Can you help me better understand why we need a custom hook to store mouse usage state?
    -   (`useUsingMouse`) <https://github.com/getflywheel/local-components/pull/309/commits/c98014fa5c5b0edce4e6d4f9adc9bf4c6683221d>
    -   Sniffing and using a custom hook for an input device feels like a code-smell and maybe hints that we need to approach the Site context menu from another direction.

2023-03-07 21:19 UTC, adamperrry commented
> * Can you help me better understand why we need a custom hook to store mouse usage state?

This is so we only focus when navigating via keyboard as opposed to clicking around - usually just to prevent focus outlines, but in this case focused buttons also have different text colors. It's not to detect an input device or anything. We do this in Local Core by adding a window listener for `mouseDown` and `keyDown`, and they either add or remove a `using-mouse` class to the `body` component accordingly. Then our focus styles are dependent on that classname being in the hierarchy. I added this internal state because the keydown listener in core only listens for `Tab` keypresses, while menus can begin navigation with arrow keys. 

I pulled it into a custom hook because I can foresee other components needing to know whether to programmatically focus something based on keyboard navigation or not. This also kind of decouples Local Components from having to check for a `using-mouse` class on the document.

> * Can you help me better understand the reasons for using a Tooltip to render the context menu? Part of me wonders if we're forcing the Tooltip component to do more than it should.

A great question that I've also wondered! We render the tooltips via React's `createPortal` tool, which we have wrapped in our own `Portal` component, so there's no external library being used. We do it so that tooltips always show on top (hopefully). This isn't an issue because we don't navigate through the menu via `Tab`, so using the arrow keys actually helps us in that regard.

But I have wondered if we're asking too much of the tooltip component, and I think until it stop providing, I kind of want to keep using it, because it has a lot of great built-in things. The click listeners are awesome, like the trigger behavior is exactly what we'd want for a context menu. Also the positioning is already built-in, and it automatically adjusts if the tooltip is overflowing, which is huge. That's the main reason I wanted to use it, was the position logic. 

I don't think there's anything inherently bad about using the tooltip and extending it to fit our needs, because it fits pretty well in this case - for example, in other places we use the ContextMenu with an arrow, and that's just a simple prop passed as opposed to all new position and style logic.

2023-03-08 22:29 UTC, bgturner approved these changes
Nice! Thanks for all the hard work on this!

---

> We do it so that tooltips always show on top (hopefully).

> But I have wondered if we're asking too much of the tooltip component, ... I kind of want to keep using it, because it has a lot of great built-in things .. click listeners are awesome [and] the positioning is already built-in ...

That makes sense and thanks for outlining those reasons!

> I actually realized a lot of this was caused by styling :focus and not :focus-visible in the button component, so I changed that

Nice! Read my mind about leaning into `:focus-visible` and CSS-only functionality!

2023-03-09 15:53 UTC, adamperrry commented on src/styles/base.scss
>  		}
Unfortunately it's specifically tied to Local Core. Which I think is fine since the repo isn't meant to be run anywhere other than Local Core

2023-03-09 15:53 UTC, merged